### ISSUE TITLE
Hay personas que su nombre no tiene coma y rompe /general

### ISSUE THREAD

**Issue by A-deLuna** [TutorFox/cetys-api#17]
![alt](http://i.snag.gy/kE3T4.jpg)

**Comment by jlvivero** [comment]
is that from the original address? If it's not, I think it's better for now, to just let access be denied to people that haven't paid to be honest

**Comment by A-deLuna** [comment]
the problem is he HAS paid, his name in every page is not separared by a comma

**Comment by jlvivero** [comment]
welp, we can't do anything about it except validate so that it only has one name when that happens... I'll look to fix that tomorrow
