### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by jlvivero** [TutorFox/cetys-api#20]
I think that since this was originally a community project, we should license it under gpl.
what do you think?

I mean the main idea is that hopefully people from future generations keep this mantained, so I think a gpl license works just fine.

**Comment by Just-Ic3** [comment]
If the project does some day get added into CETYS as a serious part of the portal environment or something similar they'll probably have an issue with the code being out here so I would vote for the MIT license.

**Comment by jlvivero** [comment]
I don't think cetys-api can be added at all, because of the way it works, if they were to enable an actual API for the school this project would become obsolete, so it wouldn't matter.

Even if it didn't since we're the owners of the code, we can change the licensing whenever we want.

At the end of the day cetys-api is a hack so it cannot be integrated with the school anyway, It's best to have a GPL type license, and try to make it so that newer students contribute and maintain it if possible as well.

**Comment by jlvivero** [comment]
@A-deLuna que opinas?

**Comment by A-deLuna** [comment]
Em, creo que cualquiera de las dos están bien, aunque favorezco la MIT por ser más permisiva. Esto para casos de que alguien esté haciendo su proyecto de progra, baje el script y le haga cambios y lo use y no tener que estarlo molestando para que haga su proyecto open source si no quiere, y pues aunque fuera gpl se me hace difícil que nos estemos dedicando a forzar a que hagan publiquen los archivos

**Comment by jlvivero** [comment]
De la misma manera, a mi me gustaria que si alguien le agrega algun feature a cetys-api, la comparta con los estudiantes del cetys.
Obviamente no vamos a buscar a la gente para que lo haga open source, pero minimo ahi esta la licencia para que traten de hacelo.
Aparte que la parte de cetys-api sea GPL no significa que no puedan hacer el resto de su codigo bajo otra licencia.

**Comment by jlvivero** [comment]
license stays as it is
